-- MySQL Script generated by MySQL Workbench
-- Sat May 25 11:36:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quake_log_parser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quake_log_parser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quake_log_parser` DEFAULT CHARACTER SET utf8 ;
USE `quake_log_parser` ;

-- -----------------------------------------------------
-- Table `quake_log_parser`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quake_log_parser`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIME NULL,
  `end` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quake_log_parser`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quake_log_parser`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quake_log_parser`.`means_of_death`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quake_log_parser`.`means_of_death` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quake_log_parser`.`kiills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quake_log_parser`.`kiills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `world_killed` TINYINT NOT NULL DEFAULT 0,
  `killed_at` TIME NULL,
  `game_id` INT NOT NULL,
  `player_kill_id` INT NULL,
  `player_killed_id` INT NOT NULL,
  `means_of_death_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kiills_games_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_kiills_players1_idx` (`player_kill_id` ASC) VISIBLE,
  INDEX `fk_kiills_means_of_death1_idx` (`means_of_death_id` ASC) VISIBLE,
  INDEX `fk_kiills_players2_idx` (`player_killed_id` ASC) VISIBLE,
  CONSTRAINT `fk_kiills_games`
    FOREIGN KEY (`game_id`)
    REFERENCES `quake_log_parser`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kiills_players1`
    FOREIGN KEY (`player_kill_id`)
    REFERENCES `quake_log_parser`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kiills_means_of_death1`
    FOREIGN KEY (`means_of_death_id`)
    REFERENCES `quake_log_parser`.`means_of_death` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kiills_players2`
    FOREIGN KEY (`player_killed_id`)
    REFERENCES `quake_log_parser`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
